Update label_checker.yml

diff --git a/.github/workflows/label_checker.yml b/.github/workflows/label_checker.yml
--- a/.github/workflows/label_checker.yml
+++ b/.github/workflows/label_checker.yml
@@ -17,23 +17,8 @@ jobs:
     runs-on: ubuntu-latest
     name: Breaking changes label checker
     steps:
-      - name: Pass if labeled
-        if: "contains(github.event.pull_request.labels.*.name, 'Breaking changes') || contains(github.event.pull_request.labels.*.name, 'Non breaking changes')"
-        run: |
-          curl -L \
-            -X POST \
-            -H "Accept: application/vnd.github+json" \
-            -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            https://api.github.com/repos/${{github.repository}}/statuses/${{github.event.pull_request.head.sha}} \
-            -d '{"state":"success","description":"Labeled. Thank you.","context":"Breaking changes label checker"}'
-      - name: Pending if not labeled
+      - name: Failed if not labeled
         if: "!(contains(github.event.pull_request.labels.*.name, 'Breaking changes') || contains(github.event.pull_request.labels.*.name, 'Non breaking changes'))"
         run: |
-          curl -L \
-            -X POST \
-            -H "Accept: application/vnd.github+json" \
-            -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            https://api.github.com/repos/${{github.repository}}/statuses/${{github.event.pull_request.head.sha}} \
-            -d '{"state":"failure","description":"Please label Breaking changes or Non Breaking changes.","context":"Breaking changes label checker"}'
+          echo "::error::Please label \"Breaking changes\" or \"Non breaking changes\"."
+          exit 1
